name: infra-apply

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
      - ".github/workflows/**"

permissions:
  contents: read

concurrency:
  group: terraform-apply-main
  cancel-in-progress: false

jobs:
  terraform:
    name: apply
    runs-on: ubuntu-latest
    
    env:
      BACKEND_HCL_CONTENT: ${{ secrets.BACKEND_HCL }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Create Backend Config
        run: echo "$BACKEND_HCL_CONTENT" > backend.hcl

      - name: Terraform Format Check
        run: make fmt-check

      - name: Terraform Init
        run: make init

      - name: Terraform Validate
        run: make validate

      - name: Terraform Plan
        run: make plan

      - name: Terraform Apply
        run: make apply